apiVersion: apps/v1
kind: Deployment
metadata:
  name: myboutique
spec:
  selector:
    matchLabels:
      app: myboutique
  replicas: 1
  template:
    metadata:
      labels:
        app: myboutique
    spec:
      containers:
        - name: myboutique
          image: docker.io/aymenbraiek2019/myboutique:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - name: myboutique
              containerPort: 9992
              protocol: TCP
      imagePullSecrets:
        - name: secret1
          env:
          - name: POSTGRES_SERVICE
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres.service.name
          - name: POSTGRES_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres.db.name
          - name: POSTGRES_DB_USER
            valueFrom:
              secretKeyRef:
                name: db-security
                key: db.user.name
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-security
                key: db.user.password
---
apiVersion: v1
kind: Service
metadata:
  name: sbapp-lb
  labels:
    app: myboutique
spec:
  type: LoadBalancer
  ports:
    - port: 9992
  selector:
    app: myboutique