apiVersion: apps/v1
kind: Deployment
metadata:
  name: myboutique
spec:
  selector:
    matchLabels:
      app: myboutique
  replicas: 1
  template:
    metadata:
      labels:
        app: myboutique
    spec:
      containers:
        - name: myboutique
          image: docker.io/aymenbraiek2019/myboutique:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - name: myboutique
              containerPort: 9992
              protocol: TCP
      imagePullSecrets:
        - name: secret1
---
apiVersion: v1
kind: Service
metadata:
  name: sbapp-lb
  labels:
    app: myboutique
spec:
  type: LoadBalancer
  ports:
    - port: 9992
  selector:
    app: myboutique