apiVersion: apps/v1
kind: Deployment
metadata:
  name: myboutique
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myboutique
  template:
    metadata:
      labels:
        app: myboutique
    spec:
      containers:
        - name: myboutique
          image: aymenbraiek2019/myboutique:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          imagePullSecrets:
            - name: secret1
          env:
            - name: POSTGRES_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres.service.name
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres.db.name
            - name: POSTGRES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-security
                  key: db.user.name
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-security
                  key: db.user.password
---
apiVersion: v1
kind: Service
metadata:
  name: myboutique-lb
  labels:
    app: myboutique
spec:
  type: LoadBalancer
  ports:
    - port: 9992
  selector:
    app: myboutique